# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-08 14:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employ_id', models.CharField(max_length=12)),
                ('job', models.CharField(max_length=12)),
                ('name', models.CharField(max_length=20)),
                ('sex', models.IntegerField(choices=[(0, '男'), (1, '女')])),
                ('position', models.IntegerField(choices=[(0, '经理'), (1, '组长'), (2, '员工')], verbose_name='职位')),
            ],
            options={
                'verbose_name': '员工',
                'verbose_name_plural': '员工',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('date', models.DateTimeField()),
                ('days', models.IntegerField(verbose_name='天数')),
                ('money', models.FloatField(verbose_name='扣款')),
                ('employ_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pay.Employs', verbose_name='员工号')),
            ],
            options={
                'verbose_name': '请假',
                'verbose_name_plural': '请假',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Prize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('money', models.FloatField(verbose_name='奖金')),
                ('employ_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pay.Employs', verbose_name='员工号')),
            ],
            options={
                'verbose_name': '奖金',
                'verbose_name_plural': '奖金',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Punish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('date', models.DateTimeField()),
                ('money', models.FloatField(verbose_name='扣款')),
                ('employ_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pay.Employs', verbose_name='员工号')),
            ],
            options={
                'verbose_name': '扣款',
                'verbose_name_plural': '扣款',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_salary', models.FloatField(verbose_name='基本工资')),
                ('date', models.DateTimeField(verbose_name='发款日期')),
                ('total_punish', models.FloatField(verbose_name='总扣款')),
                ('total_prize', models.FloatField(verbose_name='总奖金')),
                ('total_salary', models.FloatField(verbose_name='应得工资')),
                ('employ_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pay.Employs', verbose_name='员工号')),
            ],
            options={
                'verbose_name': '工资表',
                'verbose_name_plural': '工资表',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay_type', models.CharField(choices=[('银行卡', '银行卡'), ('现金', '现金'), ('支票', '支票')], max_length=20, verbose_name='付款类型')),
                ('car_number', models.CharField(blank=True, max_length=40, null=True, verbose_name='卡号')),
                ('employ_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pay.Employs', verbose_name='员工号')),
            ],
            options={
                'verbose_name': '付款类型',
                'verbose_name_plural': '付款类型',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='salary',
            name='pay_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pay.Type'),
        ),
    ]
